name: Deploy to Azure App Service

on:
  push: 
    branches: 
      - app-service-deployment

jobs: 
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Setup Node.js version
        uses: actions/setup-node@v4
        with: 
          node-version: '18.x'
      - name: Install Dependencies
      - name: Run graphql-http install
          run: ./node_modules/.bin/graphql-http install
        run: "express-graphql": "^0.12.0",
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: mywebappns
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: .       

              
